<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('tire_test_data_u', function (Blueprint $table) {
            $table->id('row_seq');
            $table->integer('id')->unique();
            $table->date('test_date')->nullable();
            $table->time('test_time')->nullable();
            $table->string('shift', 10)->nullable();
            $table->string('model_no', 50)->nullable();
            $table->string('size_code', 50)->nullable();
            $table->string('barcode', 100)->nullable();
            $table->decimal('bead_dia', 8, 3)->nullable();
            $table->decimal('air_press', 8, 3)->nullable();
            $table->decimal('load_kgf', 8, 3)->nullable();

            $table->decimal('cw_rfv_oa_val', 12, 3)->nullable();
            $table->decimal('cw_rfv_oa_deg', 8, 2)->nullable();
            $table->string('cw_rfv_oa_rank', 10)->nullable();
            $table->decimal('cw_rfv_1h_val', 12, 3)->nullable();
            $table->decimal('cw_rfv_1h_deg', 8, 2)->nullable();
            $table->string('cw_rfv_1h_rank', 10)->nullable();
            $table->decimal('cw_rfv_2h_val', 12, 3)->nullable();
            $table->decimal('cw_rfv_2h_deg', 8, 2)->nullable();
            $table->string('cw_rfv_2h_rank', 10)->nullable();
            $table->decimal('cw_rfv_3h_val', 12, 3)->nullable();
            $table->decimal('cw_rfv_3h_deg', 8, 2)->nullable();
            $table->string('cw_rfv_3h_rank', 10)->nullable();
            $table->decimal('cw_rfv_4h_val', 12, 3)->nullable();
            $table->decimal('cw_rfv_4h_deg', 8, 2)->nullable();
            $table->string('cw_rfv_4h_rank', 10)->nullable();
            $table->decimal('cw_rfv_5h_val', 12, 3)->nullable();
            $table->decimal('cw_rfv_5h_deg', 8, 2)->nullable();
            $table->string('cw_rfv_5h_rank', 10)->nullable();
            $table->decimal('cw_rfv_6h_val', 12, 3)->nullable();
            $table->decimal('cw_rfv_6h_deg', 8, 2)->nullable();
            $table->string('cw_rfv_6h_rank', 10)->nullable();
            $table->decimal('cw_rfv_7h_val', 12, 3)->nullable();
            $table->decimal('cw_rfv_7h_deg', 8, 2)->nullable();
            $table->string('cw_rfv_7h_rank', 10)->nullable();
            $table->decimal('cw_rfv_8h_val', 12, 3)->nullable();
            $table->decimal('cw_rfv_8h_deg', 8, 2)->nullable();
            $table->string('cw_rfv_8h_rank', 10)->nullable();
            $table->decimal('cw_rfv_9h_val', 12, 3)->nullable();
            $table->decimal('cw_rfv_9h_deg', 8, 2)->nullable();
            $table->string('cw_rfv_9h_rank', 10)->nullable();
            $table->decimal('cw_rfv_10h_val', 12, 3)->nullable();
            $table->decimal('cw_rfv_10h_deg', 8, 2)->nullable();
            $table->string('cw_rfv_10h_rank', 10)->nullable();
            $table->decimal('cw_lfv_oa_val', 12, 3)->nullable();
            $table->decimal('cw_lfv_oa_deg', 8, 2)->nullable();
            $table->string('cw_lfv_oa_rank', 10)->nullable();
            $table->decimal('cw_lfv_1h_val', 12, 3)->nullable();
            $table->decimal('cw_lfv_1h_deg', 8, 2)->nullable();
            $table->string('cw_lfv_1h_rank', 10)->nullable();
            $table->decimal('cw_lfv_2h_val', 12, 3)->nullable();
            $table->decimal('cw_lfv_2h_deg', 8, 2)->nullable();
            $table->string('cw_lfv_2h_rank', 10)->nullable();
            $table->decimal('cw_lfv_3h_val', 12, 3)->nullable();
            $table->decimal('cw_lfv_3h_deg', 8, 2)->nullable();
            $table->string('cw_lfv_3h_rank', 10)->nullable();
            $table->decimal('cw_lfv_4h_val', 12, 3)->nullable();
            $table->decimal('cw_lfv_4h_deg', 8, 2)->nullable();
            $table->string('cw_lfv_4h_rank', 10)->nullable();
            $table->decimal('cw_lfv_5h_val', 12, 3)->nullable();
            $table->decimal('cw_lfv_5h_deg', 8, 2)->nullable();
            $table->string('cw_lfv_5h_rank', 10)->nullable();
            $table->decimal('cw_lfv_6h_val', 12, 3)->nullable();
            $table->decimal('cw_lfv_6h_deg', 8, 2)->nullable();
            $table->string('cw_lfv_6h_rank', 10)->nullable();
            $table->decimal('cw_lfv_7h_val', 12, 3)->nullable();
            $table->decimal('cw_lfv_7h_deg', 8, 2)->nullable();
            $table->string('cw_lfv_7h_rank', 10)->nullable();
            $table->decimal('cw_lfv_8h_val', 12, 3)->nullable();
            $table->decimal('cw_lfv_8h_deg', 8, 2)->nullable();
            $table->string('cw_lfv_8h_rank', 10)->nullable();
            $table->decimal('cw_lfv_9h_val', 12, 3)->nullable();
            $table->decimal('cw_lfv_9h_deg', 8, 2)->nullable();
            $table->string('cw_lfv_9h_rank', 10)->nullable();
            $table->decimal('cw_lfv_10h_val', 12, 3)->nullable();
            $table->decimal('cw_lfv_10h_deg', 8, 2)->nullable();
            $table->string('cw_lfv_10h_rank', 10)->nullable();
            $table->decimal('ccw_rfv_oa_val', 12, 3)->nullable();
            $table->decimal('ccw_rfv_oa_deg', 8, 2)->nullable();
            $table->string('ccw_rfv_oa_rank', 10)->nullable();
            $table->decimal('ccw_rfv_1h_val', 12, 3)->nullable();
            $table->decimal('ccw_rfv_1h_deg', 8, 2)->nullable();
            $table->string('ccw_rfv_1h_rank', 10)->nullable();
            $table->decimal('ccw_rfv_2h_val', 12, 3)->nullable();
            $table->decimal('ccw_rfv_2h_deg', 8, 2)->nullable();
            $table->string('ccw_rfv_2h_rank', 10)->nullable();
            $table->decimal('ccw_rfv_3h_val', 12, 3)->nullable();
            $table->decimal('ccw_rfv_3h_deg', 8, 2)->nullable();
            $table->string('ccw_rfv_3h_rank', 10)->nullable();
            $table->decimal('ccw_rfv_4h_val', 12, 3)->nullable();
            $table->decimal('ccw_rfv_4h_deg', 8, 2)->nullable();
            $table->string('ccw_rfv_4h_rank', 10)->nullable();
            $table->decimal('ccw_rfv_5h_val', 12, 3)->nullable();
            $table->decimal('ccw_rfv_5h_deg', 8, 2)->nullable();
            $table->string('ccw_rfv_5h_rank', 10)->nullable();
            $table->decimal('ccw_rfv_6h_val', 12, 3)->nullable();
            $table->decimal('ccw_rfv_6h_deg', 8, 2)->nullable();
            $table->string('ccw_rfv_6h_rank', 10)->nullable();
            $table->decimal('ccw_rfv_7h_val', 12, 3)->nullable();
            $table->decimal('ccw_rfv_7h_deg', 8, 2)->nullable();
            $table->string('ccw_rfv_7h_rank', 10)->nullable();
            $table->decimal('ccw_rfv_8h_val', 12, 3)->nullable();
            $table->decimal('ccw_rfv_8h_deg', 8, 2)->nullable();
            $table->string('ccw_rfv_8h_rank', 10)->nullable();
            $table->decimal('ccw_rfv_9h_val', 12, 3)->nullable();
            $table->decimal('ccw_rfv_9h_deg', 8, 2)->nullable();
            $table->string('ccw_rfv_9h_rank', 10)->nullable();
            $table->decimal('ccw_rfv_10h_val', 12, 3)->nullable();
            $table->decimal('ccw_rfv_10h_deg', 8, 2)->nullable();
            $table->string('ccw_rfv_10h_rank', 10)->nullable();
            $table->decimal('ccw_lfv_oa_val', 12, 3)->nullable();
            $table->decimal('ccw_lfv_oa_deg', 8, 2)->nullable();
            $table->string('ccw_lfv_oa_rank', 10)->nullable();
            $table->decimal('ccw_lfv_1h_val', 12, 3)->nullable();
            $table->decimal('ccw_lfv_1h_deg', 8, 2)->nullable();
            $table->string('ccw_lfv_1h_rank', 10)->nullable();
            $table->decimal('ccw_lfv_2h_val', 12, 3)->nullable();
            $table->decimal('ccw_lfv_2h_deg', 8, 2)->nullable();
            $table->string('ccw_lfv_2h_rank', 10)->nullable();
            $table->decimal('ccw_lfv_3h_val', 12, 3)->nullable();
            $table->decimal('ccw_lfv_3h_deg', 8, 2)->nullable();
            $table->string('ccw_lfv_3h_rank', 10)->nullable();
            $table->decimal('ccw_lfv_4h_val', 12, 3)->nullable();
            $table->decimal('ccw_lfv_4h_deg', 8, 2)->nullable();
            $table->string('ccw_lfv_4h_rank', 10)->nullable();
            $table->decimal('ccw_lfv_5h_val', 12, 3)->nullable();
            $table->decimal('ccw_lfv_5h_deg', 8, 2)->nullable();
            $table->string('ccw_lfv_5h_rank', 10)->nullable();
            $table->decimal('ccw_lfv_6h_val', 12, 3)->nullable();
            $table->decimal('ccw_lfv_6h_deg', 8, 2)->nullable();
            $table->string('ccw_lfv_6h_rank', 10)->nullable();
            $table->decimal('ccw_lfv_7h_val', 12, 3)->nullable();
            $table->decimal('ccw_lfv_7h_deg', 8, 2)->nullable();
            $table->string('ccw_lfv_7h_rank', 10)->nullable();
            $table->decimal('ccw_lfv_8h_val', 12, 3)->nullable();
            $table->decimal('ccw_lfv_8h_deg', 8, 2)->nullable();
            $table->string('ccw_lfv_8h_rank', 10)->nullable();
            $table->decimal('ccw_lfv_9h_val', 12, 3)->nullable();
            $table->decimal('ccw_lfv_9h_deg', 8, 2)->nullable();
            $table->string('ccw_lfv_9h_rank', 10)->nullable();
            $table->decimal('ccw_lfv_10h_val', 12, 3)->nullable();
            $table->decimal('ccw_lfv_10h_deg', 8, 2)->nullable();
            $table->string('ccw_lfv_10h_rank', 10)->nullable();
            $table->decimal('cw_lfd_val', 12, 3)->nullable();
            $table->string('cw_lfd_rank', 10)->nullable();
            $table->decimal('ccw_lfd_val', 12, 3)->nullable();
            $table->string('ccw_lfd_rank', 10)->nullable();
            $table->decimal('con_val', 12, 3)->nullable();
            $table->string('con_rank', 10)->nullable();
            $table->decimal('ply_val', 12, 3)->nullable();
            $table->string('ply_rank', 10)->nullable();
            $table->string('ufm_rank', 10)->nullable();
            $table->decimal('lt_oa_val', 12, 3)->nullable();
            $table->decimal('lt_oa_deg', 8, 2)->nullable();
            $table->string('lt_oa_rank', 10)->nullable();
            $table->decimal('lt_1h_val', 12, 3)->nullable();
            $table->decimal('lt_1h_deg', 8, 2)->nullable();
            $table->string('lt_1h_rank', 10)->nullable();
            $table->decimal('lb_oa_val', 12, 3)->nullable();
            $table->decimal('lb_oa_deg', 8, 2)->nullable();
            $table->string('lb_oa_rank', 10)->nullable();
            $table->decimal('lb_1h_val', 12, 3)->nullable();
            $table->decimal('lb_1h_deg', 8, 2)->nullable();
            $table->string('lb_1h_rank', 10)->nullable();
            $table->decimal('rt_oa_val', 12, 3)->nullable();
            $table->decimal('rt_oa_deg', 8, 2)->nullable();
            $table->string('rt_oa_rank', 10)->nullable();
            $table->decimal('rt_1h_val', 12, 3)->nullable();
            $table->decimal('rt_1h_deg', 8, 2)->nullable();
            $table->string('rt_1h_rank', 10)->nullable();
            $table->decimal('rc_oa_val', 12, 3)->nullable();
            $table->decimal('rc_oa_deg', 8, 2)->nullable();
            $table->string('rc_oa_rank', 10)->nullable();
            $table->decimal('rc_1h_val', 12, 3)->nullable();
            $table->decimal('rc_1h_deg', 8, 2)->nullable();
            $table->string('rc_1h_rank', 10)->nullable();
            $table->decimal('rb_oa_val', 12, 3)->nullable();
            $table->decimal('rb_oa_deg', 8, 2)->nullable();
            $table->string('rb_oa_rank', 10)->nullable();
            $table->decimal('rb_1h_val', 12, 3)->nullable();
            $table->decimal('rb_1h_deg', 8, 2)->nullable();
            $table->string('rb_1h_rank', 10)->nullable();
            $table->decimal('lt_bulg_val', 12, 3)->nullable();
            $table->decimal('lt_bulg_deg', 8, 2)->nullable();
            $table->string('lt_bulg_rank', 10)->nullable();
            $table->decimal('lt_dent_val', 12, 3)->nullable();
            $table->decimal('lt_dent_deg', 8, 2)->nullable();
            $table->string('lt_dent_rank', 10)->nullable();
            $table->decimal('lb_bulg_val', 12, 3)->nullable();
            $table->decimal('lb_bulg_deg', 8, 2)->nullable();
            $table->string('lb_bulg_rank', 10)->nullable();
            $table->decimal('lb_dent_val', 12, 3)->nullable();
            $table->decimal('lb_dent_deg', 8, 2)->nullable();
            $table->string('lb_dent_rank', 10)->nullable();
            $table->string('ro_rank', 10)->nullable();
            $table->decimal('upper_val', 12, 3)->nullable();
            $table->decimal('upper_deg', 8, 2)->nullable();
            $table->string('upper_rank', 10)->nullable();
            $table->decimal('lower_val', 12, 3)->nullable();
            $table->decimal('lower_deg', 8, 2)->nullable();
            $table->string('lower_rank', 10)->nullable();
            $table->decimal('static_val', 12, 3)->nullable();
            $table->decimal('static_deg', 8, 2)->nullable();
            $table->string('static_rank', 10)->nullable();
            $table->decimal('couple_val', 12, 3)->nullable();
            $table->decimal('couple_deg', 8, 2)->nullable();
            $table->string('couple_rank', 10)->nullable();
            $table->decimal('up_low_val', 12, 3)->nullable();
            $table->string('up_low_rank', 10)->nullable();
            $table->string('bal_rank', 10)->nullable();
            $table->string('total_rank', 10)->nullable();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('tire_test_data_u');
    }
};
